@host = http://localhost:9090

### 매출 조회 - 전체 크리에이터, 2026-05 한 달
GET {{host}}/api/sales?from=2026-05-01T00:00:00&toExclusive=2026-06-01T00:00:00

### 매출 조회 - 특정 크리에이터 (creatorId=1), 2026-05 한 달
GET {{host}}/api/sales?creatorId=2&from=2026-05-01T00:00:00&toExclusive=2026-06-01T00:00:00

### 매출 조회 - 일간 조회 (2026-05-22 하루)
GET {{host}}/api/sales?from=2026-05-22T00:00:00&toExclusive=2026-05-23T00:00:00

### 매출 조회 - validation 실패 확인용 (from 누락)
GET {{host}}/api/sales?toExclusive=2026-06-01T00:00:00
